# Generated by Django 5.1.7 on 2025-03-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('PERSONAL', 'personal object'), ('INVENTION', 'invention'), ('NOTES', 'notes')], default='PERSONAL', max_length=20),
        ),
    ]
