# Generated by Django 5.1.7 on 2025-04-14 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_item_id_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default='2000-01-01')),
                ('type', models.CharField(choices=[('RESTORATION', 'restoration'), ('REPAIR', 'repair'), ('CLEANING', 'cleaning')], default='RESTORATION', max_length=20)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.event'),
        ),
    ]
