# Generated by Django 5.1.7 on 2025-04-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_event_restoration_item_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoration',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.item'),
        ),
    ]
